// <auto-generated />
namespace CourseProject_WPF_.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class qq : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(qq));
        
        string IMigrationMetadata.Id
        {
            get { return "202105250950210_qq"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
